Update terminal-table workaround problem
```
rake aborted!
NoMethodError: undefined method `all_separators=' for #<Terminal::Table::Style:0x007f94e9fe32d0>
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/gems/terminal-table-1.5.2/lib/terminal-table/style.rb:48:in `block in apply'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/gems/terminal-table-1.5.2/lib/terminal-table/style.rb:48:in `each'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/gems/terminal-table-1.5.2/lib/terminal-table/style.rb:48:in `apply'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/gems/terminal-table-1.5.2/lib/terminal-table/table.rb:143:in `style='
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/bundler/gems/routes_to_swagger_docs-c23a56fa19df/lib/routes_to_swagger_docs/tool/paths/stats.rb:39:in `block (2 levels) in table'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/bundler/gems/routes_to_swagger_docs-c23a56fa19df/lib/routes_to_swagger_docs/tool/paths/stats.rb:36:in `each'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/bundler/gems/routes_to_swagger_docs-c23a56fa19df/lib/routes_to_swagger_docs/tool/paths/stats.rb:36:in `each_with_index'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/bundler/gems/routes_to_swagger_docs-c23a56fa19df/lib/routes_to_swagger_docs/tool/paths/stats.rb:36:in `block in table'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/gems/terminal-table-1.5.2/lib/terminal-table/table.rb:216:in `yield_or_eval'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/gems/terminal-table-1.5.2/lib/terminal-table/table.rb:17:in `initialize'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/bundler/gems/routes_to_swagger_docs-c23a56fa19df/lib/routes_to_swagger_docs/tool/paths/stats.rb:35:in `new'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/bundler/gems/routes_to_swagger_docs-c23a56fa19df/lib/routes_to_swagger_docs/tool/paths/stats.rb:35:in `table'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/bundler/gems/routes_to_swagger_docs-c23a56fa19df/lib/routes_to_swagger_docs/tool/paths/stats.rb:25:in `print'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/bundler/gems/routes_to_swagger_docs-c23a56fa19df/lib/routes_to_swagger_docs/tasks/tool.rake:61:in `block (3 levels) in <top (required)>'
/Users/fukudayu/Zenlogic/phoenix-development-kit/projects/leonacore/work/vendor/bundle/ruby/2.3.0/bundler/gems/routes_to_swagger_docs-c23a56fa19df/lib/routes_to_swagger_docs/task_logging.rb:11:in `block in task'
/Users/fukudayu/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
/Users/fukudayu/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
Tasks: TOP => routes:swagger:paths_stats
(See full trace by running task with --trace)
```